"""atualizar campos nulos para falso

Revision ID: 815d6b150d2d
Revises: f55cf27081fa
Create Date: 2025-02-25 20:19:25.088844

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "815d6b150d2d"
down_revision: Union[str, None] = "f55cf27081fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
